name: aphrodite
channels:
  - nvidia
  - pytorch
  - nvidia/label/cuda-12.1.1
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pytorch=2.3.0
  - pytorch-cuda=12.1.*
  - cuda-nvcc=12.1.*
  - cuda-libraries-dev=12.1.*
  - cuda=12.1.*
  - cuda-version=12.1.*
  - nccl
  - cxx-compiler
  - gxx=11.3
  - pip
  - git=2.35.1
  - ninja